#!/usr/bin/env bash
# Start the shareable Copepod Assistant stack.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

AGENT_MODE="container"
BUILD_MODE="no-build"

for arg in "$@"; do
  case "$arg" in
    --local-agent)
      AGENT_MODE="local"
      ;;
    --build)
      BUILD_MODE="build"
      ;;
    --help|-h)
      echo "Usage: ./start.sh [--local-agent] [--build]"
      echo ""
      echo "Default: start Postgres, MCP EcoTaxa, copepod-agent, and Open WebUI in Docker without rebuilding images."
      echo "--local-agent: do not start the copepod-agent container; Open WebUI points to a local agent on localhost:8000."
      echo "--build: allow Docker Compose to build images if needed."
      exit 0
      ;;
    *)
      echo "[start] Unknown option: $arg"
      echo "Usage: ./start.sh [--local-agent] [--build]"
      exit 1
      ;;
  esac
done

REQUIRED_ENV_VARS=(
  OPENAI_API_KEY
  ECOTAXA_USERNAME
  ECOTAXA_PASSWORD
  LANGCHAIN_API_KEY
)

generate_mcp_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import secrets; print(secrets.token_urlsafe(48))'
  else
    echo "mcp-$(date +%s)-$RANDOM-$RANDOM"
  fi
}

if [ ! -f .env ]; then
  cp .env.example .env
  echo "[start] Created .env from .env.example."
  echo "[start] Fill only these values, then run ./start.sh again:"
  printf "        - %s\n" "${REQUIRED_ENV_VARS[@]}"
  echo "[start] MCP_AUTH_TOKEN will be generated automatically."
  exit 1
fi

set -a
source .env
set +a

missing=()
for var_name in "${REQUIRED_ENV_VARS[@]}"; do
  value="${!var_name:-}"
  if [ -z "$value" ] || [[ "$value" == REPLACE_WITH_* ]]; then
    missing+=("$var_name")
  fi
done

if [ "${#missing[@]}" -gt 0 ]; then
  echo "[start] .env is incomplete."
  echo "[start] Fill only these values and leave everything else unchanged:"
  printf "        - %s\n" "${missing[@]}"
  echo "[start] MCP_AUTH_TOKEN will be generated automatically."
  exit 1
fi

if [ -z "${MCP_AUTH_TOKEN:-}" ] || [[ "${MCP_AUTH_TOKEN:-}" == REPLACE_WITH_* ]]; then
  MCP_AUTH_TOKEN="$(generate_mcp_token)"
  export MCP_AUTH_TOKEN
  {
    echo ""
    echo "# Generated by ./start.sh. Do not edit."
    echo "MCP_AUTH_TOKEN=$MCP_AUTH_TOKEN"
  } >> .env
  echo "[start] Generated MCP_AUTH_TOKEN in .env."
fi

if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
  echo "[start] Docker with docker compose is required."
  echo "[start] Start Docker Desktop, then run ./start.sh again."
  exit 1
fi

# The compose file bind-mounts the clone into the container (.:/app): the code
# that runs is THIS checkout, not the published image. Warn when it lags main.
if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  if git fetch --quiet origin main 2>/dev/null; then
    BEHIND_COUNT="$(git rev-list --count HEAD..origin/main 2>/dev/null || echo 0)"
    if [ "$BEHIND_COUNT" -gt 0 ]; then
      echo "[start] WARNING: this clone is ${BEHIND_COUNT} commit(s) behind origin/main."
      echo "[start] The agent runs YOUR local code — run 'git pull' to get the latest version."
    fi
  fi
fi

if [ "$AGENT_MODE" = "local" ]; then
  export OPENWEBUI_AGENT_BASE_URL="http://host.docker.internal:8000/v1"
  SERVICES=(postgres mcp-ecotaxa open-webui)
  echo "[start] Starting containers without copepod-agent..."
  echo "[start] Open WebUI will use the local agent at http://localhost:8000."
else
  # copepod-agent is started only AFTER the EcoTaxa cache preflight passes, so
  # the agent never comes up on top of an empty or broken cache.
  SERVICES=(postgres mcp-ecotaxa open-webui)
  echo "[start] Starting containers (agent starts after the cache check)..."
fi

if [ "$BUILD_MODE" = "build" ]; then
  docker compose up -d "${SERVICES[@]}"
else
  docker compose up -d --no-build "${SERVICES[@]}" || {
    echo "[start] Docker image missing. Run once with ./start.sh --build, or pull the published images."
    exit 1
  }
fi

echo "[start] Waiting for Postgres..."
until docker compose exec -T postgres pg_isready -U copepod -d copepod_sessions -q >/dev/null 2>&1; do
  sleep 1
done
echo "[start] Postgres OK"

echo "[start] Waiting for MCP EcoTaxa..."
until docker compose exec -T mcp-ecotaxa curl -sf http://localhost:8001/health >/dev/null 2>&1; do
  sleep 1
done
echo "[start] MCP EcoTaxa OK"

# First boot builds the account's cache from a live EcoTaxa sync, kicked off in
# the background as soon as the MCP server sees an empty cache. That sync takes
# a bit, so the preflight below would otherwise read an as-yet-empty cache,
# fail, and force a needless second ./start.sh. Wait for the sync to reach a
# usable state first. Bounded by ECOTAXA_SYNC_WAIT_SECONDS (default 600).
# A populated cache is released only when its schema is also current: an old
# "ok" sync from a v2 cache must not race the v3 metadata refresh.
SYNC_WAIT_MAX="${ECOTAXA_SYNC_WAIT_SECONDS:-600}"
echo "[start] Waiting for the initial EcoTaxa cache sync (up to ${SYNC_WAIT_MAX}s)..."
sync_waited=0
sync_start=$(date +%s)
while [ "$sync_waited" -lt "$SYNC_WAIT_MAX" ]; do
  SYNC_HEALTH="$(docker compose exec -T mcp-ecotaxa curl -sf http://localhost:8001/health 2>/dev/null || true)"
  if [[ "$SYNC_HEALTH" == *'"schema_current":true'* ]] && \
     { [[ "$SYNC_HEALTH" == *'"last_sync_status":"ok"'* ]] || \
       [[ "$SYNC_HEALTH" == *'"last_sync_status":"partial"'* ]]; }; then
    sync_elapsed=$(( $(date +%s) - sync_start ))
    printf "[start] Cache EcoTaxa synchronisé en %ds.\n" "$sync_elapsed"
    break
  fi
  case "$SYNC_HEALTH" in
    *'"last_sync_status":"error"'*|*'"last_sync_status":"failed"'*)
      echo "[start] Initial sync reported an error — continuing to the cache check for details."
      break
      ;;
  esac
  sleep 5
  sync_waited=$((sync_waited + 5))
done
if [ "$sync_waited" -ge "$SYNC_WAIT_MAX" ]; then
  echo "[start] WARNING: sync did not finish within ${SYNC_WAIT_MAX}s — running the cache check anyway."
fi

# Cache preflight: gate the agent on a populated, readable EcoTaxa cache.
# Runs inside the MCP container (has python3 + the bind-mounted script) so it
# does not depend on a host python. A non-zero exit blocks startup entirely —
# whoever runs ./start.sh gets a guaranteed-good cache or a clear failure.
echo "[start] Checking EcoTaxa cache health..."
preflight_start=$(date +%s)
if ! docker compose exec -T mcp-ecotaxa sh -c \
     'curl -sf http://localhost:8001/health | python3 scripts/check_ecotaxa_cache.py'; then
  echo "[start] EcoTaxa cache preflight FAILED — agent will NOT start."
  echo "[start] Fix options:"
  echo "[start]   - Trigger a sync: POST http://localhost:8001/admin/resync (with the MCP token)"
  echo "[start]   - Verify ECOTAXA_USERNAME / ECOTAXA_PASSWORD in .env"
  echo "[start]   - Confirm ECOTAXA_CACHE_DB points at a populated cache file"
  echo "[start] Then run ./start.sh again."
  exit 1
fi
preflight_elapsed=$(( $(date +%s) - preflight_start ))
total_cache_elapsed=$(( $(date +%s) - sync_start ))
echo ""
echo "  Cache EcoTaxa : OK (verification en ${preflight_elapsed}s — total ${total_cache_elapsed}s)"
echo ""

if [ "$AGENT_MODE" = "local" ]; then
  LOCAL_AGENT_PID=""
  LOCAL_AGENT_LOG="${TMPDIR:-/tmp}/copepod-agent-local.log"
  if curl -sf http://localhost:8000/ >/dev/null 2>&1; then
    echo "[start] Local agent already responding on http://localhost:8000."
  else
    if [ -x ".venv/bin/python" ]; then
      AGENT_PYTHON=".venv/bin/python"
    else
      AGENT_PYTHON="python"
    fi
    echo "[start] Launching local agent: ${AGENT_PYTHON} serve.py (logs: ${LOCAL_AGENT_LOG})"
    "${AGENT_PYTHON}" serve.py > "${LOCAL_AGENT_LOG}" 2>&1 &
    LOCAL_AGENT_PID=$!
  fi
  echo "[start] Waiting for local agent API on http://localhost:8000..."
  until curl -sf http://localhost:8000/ >/dev/null 2>&1; do
    if [ -n "$LOCAL_AGENT_PID" ] && ! kill -0 "$LOCAL_AGENT_PID" 2>/dev/null; then
      echo "[start] Local agent died before responding. Last log lines:"
      tail -20 "${LOCAL_AGENT_LOG}" || true
      exit 1
    fi
    sleep 1
  done
  echo "[start] Local agent API OK"
else
  echo "[start] Cache OK — starting copepod-agent..."
  if [ "$BUILD_MODE" = "build" ]; then
    docker compose up -d copepod-agent
  else
    docker compose up -d --no-build copepod-agent || {
      echo "[start] Docker image missing. Run once with ./start.sh --build, or pull the published images."
      exit 1
    }
  fi
  echo "[start] Waiting for the agent API container..."
  until docker compose exec -T copepod-agent curl -sf http://localhost:8000/ >/dev/null 2>&1; do
    sleep 1
  done
  echo "[start] Agent API OK"
fi

LAN_IP=$(ipconfig getifaddr en0 2>/dev/null \
  || ipconfig getifaddr en1 2>/dev/null \
  || hostname -I 2>/dev/null | awk '{print $1}' \
  || echo "localhost")

SHARE_URL="http://${LAN_IP}:3000"

TUNNEL_PID=""
TUNNEL_LOG="logs/cloudflared.log"
TUNNEL_URL=""
SERVE_TUNNEL_PID=""
SERVE_TUNNEL_LOG="logs/cloudflared-serve.log"
SERVE_TUNNEL_URL=""

if command -v cloudflared >/dev/null 2>&1; then
  mkdir -p logs
  : > "$TUNNEL_LOG"
  : > "$SERVE_TUNNEL_LOG"
  echo "[start] Starting Cloudflare tunnels for Open WebUI (:3000) and agent API (:8000)..."
  cloudflared tunnel --url http://localhost:3000 --no-autoupdate > "$TUNNEL_LOG" 2>&1 &
  TUNNEL_PID=$!
  cloudflared tunnel --url http://localhost:8000 --no-autoupdate > "$SERVE_TUNNEL_LOG" 2>&1 &
  SERVE_TUNNEL_PID=$!

  for _ in $(seq 1 30); do
    [ -z "$TUNNEL_URL" ] && \
      TUNNEL_URL=$( { grep -oE 'https://[a-zA-Z0-9-]+\.trycloudflare\.com' "$TUNNEL_LOG" 2>/dev/null || true; } | head -1)
    [ -z "$SERVE_TUNNEL_URL" ] && \
      SERVE_TUNNEL_URL=$( { grep -oE 'https://[a-zA-Z0-9-]+\.trycloudflare\.com' "$SERVE_TUNNEL_LOG" 2>/dev/null || true; } | head -1)
    [ -n "$TUNNEL_URL" ] && [ -n "$SERVE_TUNNEL_URL" ] && break
    sleep 0.5
  done

  if [ -n "$SERVE_TUNNEL_URL" ]; then
    if [ "$AGENT_MODE" = "local" ]; then
      echo "[start] Agent API public URL: ${SERVE_TUNNEL_URL}"
      echo "[start] For public file links in local-agent mode, restart your local agent with SERVE_BASE_URL=${SERVE_TUNNEL_URL}."
    else
      echo "[start] Updating agent public file URL..."
      if [ "$BUILD_MODE" = "build" ]; then
        SERVE_BASE_URL="$SERVE_TUNNEL_URL" docker compose up -d --no-deps copepod-agent
      else
        SERVE_BASE_URL="$SERVE_TUNNEL_URL" docker compose up -d --no-build --no-deps copepod-agent
      fi
    fi
  fi
fi

cleanup() {
  echo ""
  echo "[start] Stopping containers..."
  for pid in "$TUNNEL_PID" "$SERVE_TUNNEL_PID" "${LOCAL_AGENT_PID:-}"; do
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      for _ in 1 2 3 4 5; do
        kill -0 "$pid" 2>/dev/null || break
        sleep 0.3
      done
      kill -9 "$pid" 2>/dev/null || true
    fi
  done
  pkill -f "cloudflared tunnel --url http://localhost:3000" 2>/dev/null || true
  pkill -f "cloudflared tunnel --url http://localhost:8000" 2>/dev/null || true
  if [ "$AGENT_MODE" = "local" ]; then
    docker compose stop open-webui mcp-ecotaxa postgres
  else
    docker compose stop open-webui copepod-agent mcp-ecotaxa postgres
  fi
  exit 0
}
trap cleanup INT TERM EXIT

echo ""
echo "Copepod Assistant"
echo "  Mode      : ${AGENT_MODE} agent"
echo "  Build     : ${BUILD_MODE}"
echo "  Open WebUI: http://localhost:3000"
echo "  LAN       : ${SHARE_URL}"
if [ -n "$TUNNEL_URL" ]; then
  echo "  Public    : ${TUNNEL_URL}"
elif [ -n "$TUNNEL_PID" ]; then
  echo "  Public    : tunnel starting, see ${TUNNEL_LOG}"
else
  echo "  Public    : install cloudflared for a temporary public URL"
fi
if [ -n "$SERVE_TUNNEL_URL" ]; then
  echo "  Agent API : ${SERVE_TUNNEL_URL}"
fi
echo ""
echo "[start] Press Ctrl+C to stop the containers started by this script."

while true; do
  sleep 3600
done
