DATA_UNDERSTANDING_DRAFT_REQUIRED = "data_understanding_draft_required"
DATA_UNDERSTANDING_CONFIRMATION_REQUIRED = "data_understanding_confirmation_required"
GRAPH_CONTEXT_DRAFT_REQUIRED = "graph_context_draft_required"
GRAPH_CONTEXT_CONFIRMATION_REQUIRED = "graph_context_confirmation_required"
PLAN_READY = "plan_ready"

DEFAULT_PHASE = DATA_UNDERSTANDING_DRAFT_REQUIRED

VALID_PHASES = {
    DATA_UNDERSTANDING_DRAFT_REQUIRED,
    DATA_UNDERSTANDING_CONFIRMATION_REQUIRED,
    GRAPH_CONTEXT_DRAFT_REQUIRED,
    GRAPH_CONTEXT_CONFIRMATION_REQUIRED,
    PLAN_READY,
}
