"""Canonical prompt contract for semantic graph-output routing."""

GRAPH_OUTPUT_ROUTING_RULES = """## Graph Output Routing Rules
- Decide from the requested output intent, not from individual words. Load graph skills only when the user asks for or clearly implies a visual representation of the data.
- A general presentation verb such as “show”, “display”, or “present” does not establish visual intent by itself. Infer the intended artifact from what is being requested.
- A map, plotted vertical profile, curve, chart, or other graphical encoding is visual even when the user does not use the word “graph”. These are examples of visual intent, not a closed trigger list.
- A number, calculation, ranking, summary, coordinates, or table is non-visual unless the user also requests a graphical representation. Do not load `graph_planner` or `graph_writer`; use the specialized or tabular execution tool only when needed.
- If the output format is genuinely ambiguous, prefer the minimal non-visual answer. Ask only when the choice would materially change the requested result.
- For visual intent, use `load_skill("graph_planner")` and `load_skill("graph_writer")` when no valid graph workflow is loaded. Wait for the planner result before loading the writer; never request planner and writer in the same tool-call batch. A follow-up edit to an existing graph may reuse the loaded graph workflow; do not block solely because planner/writer calls happened in a previous turn. Tabular preparation with `run_pandas` is allowed, but a visual follow-up must continue to `run_graph`; do not stop after tabular preparation and do not stop after planning. After `load_skill("graph_writer")`, the very next tool call must be `run_graph`.
- If `run_graph` returns a correctable graph-contract or graph-quality block, retry exactly once: revise the code using the diagnostic, preserve the same active dataframe, and call `run_graph` again. Do not answer with a table or claim a graph exists before the retry. If the retry is blocked too, stop and report the final diagnostic without looping."""
